### ISSUE TITLE
new position is not stored after changed

### ISSUE THREAD

**Issue by ph0ngp** [lawloretienne/DiscreteSlider#9]
whenever `onPositionChanged` is called, I have to call `setPosition` to make the new position permanent. Is this an expected thing to do or is it a bug?

**Comment by lawloretienne** [comment]
Can you give me more details about what exactly is happening?  Are you having an issue with the sample or with a custom implementation that you are doing?

**Comment by ph0ngp** [comment]
I'm just trying to implement it in my activity

Here is my Activity

``` java
public class MyActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final DiscreteSlider mySlider = (DiscreteSlider) findViewById(R.id.my_slider);
        mySlider.setTickMarkCount(6);
        mySlider.setPosition(2);
        mySlider.setOnDiscreteSliderChangeListener(new DiscreteSlider.OnDiscreteSliderChangeListener() {
            @Override
            public void onPositionChanged(int position) {
                System.out.println("changed to: " + position);
            }
        });
        findViewById(R.id.my_button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                System.out.println("position: " + mySlider.getPosition());
            }
        });
    }
}
```

Here is my layout `activity_main.xml`

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">

    <Button android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/my_button"/>
    <com.etiennelawlor.discreteslider.library.ui.DiscreteSlider
            android:id="@+id/my_slider"
            android:layout_width="match_parent"
            android:layout_height="30dp"/>
</LinearLayout>
```

Here is the output:

```
System.out: changed to: 3
System.out: position: 2
System.out: changed to: 4
System.out: position: 2
System.out: changed to: 1
System.out: changed to: 5
System.out: position: 2
```

I'm running Android 6.0.1

**Comment by lawloretienne** [comment]
This is now fixed in version 0.0.9.  It should be live in a few hours.

**Comment by wisien92** [comment]
slider.position is still the same after scrolling in 0.0.9 so in order to get current position I have to implement callback which is not ideal
